executors:
  awscli:
    working_directory: ~/repo
    docker:
      - image: xueshanf/awscli
        entrypoint: '/bin/bash'

version: 2.1

jobs:
  build:
    executor: awscli
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
