version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  publish:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install Git LFS
          command: |
            wget -O lfs.deb https://packagecloud.io/github/git-lfs/packages/debian/stretch/git-lfs_2.7.2_amd64.deb/download
            sudo dpkg -i lfs.deb

            git lfs install
            git lfs pull

      - run: ./publish.sh

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          context: libreoffice-lambda-layer
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
