version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  publish:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure
      - run: ./publish.sh

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          context: libreoffice-lambda-layer
